FROM node:10-alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install
#RUN npm install cheerio

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "node", "index.js" ]