FROM node:10-alpine

# Create app directory
WORKDIR /usr/src/webapp

# Install app dependencies
COPY package*.json ./
RUN npm install
# RUN npm install react-scripts
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 3000
EXPOSE 35729
CMD [ "npm", "run", "start" ]